/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JarAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JarAttributes{}

// JarAttributes struct for JarAttributes
type JarAttributes struct {
	// bank of jar
	Bank string `json:"bank"`
	// url of jar
	Url string `json:"url"`
}

type _JarAttributes JarAttributes

// NewJarAttributes instantiates a new JarAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJarAttributes(bank string, url string) *JarAttributes {
	this := JarAttributes{}
	this.Bank = bank
	this.Url = url
	return &this
}

// NewJarAttributesWithDefaults instantiates a new JarAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJarAttributesWithDefaults() *JarAttributes {
	this := JarAttributes{}
	return &this
}

// GetBank returns the Bank field value
func (o *JarAttributes) GetBank() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bank
}

// GetBankOk returns a tuple with the Bank field value
// and a boolean to check if the value has been set.
func (o *JarAttributes) GetBankOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bank, true
}

// SetBank sets field value
func (o *JarAttributes) SetBank(v string) {
	o.Bank = v
}

// GetUrl returns the Url field value
func (o *JarAttributes) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *JarAttributes) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *JarAttributes) SetUrl(v string) {
	o.Url = v
}

func (o JarAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JarAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank"] = o.Bank
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *JarAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJarAttributes := _JarAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJarAttributes)

	if err != nil {
		return err
	}

	*o = JarAttributes(varJarAttributes)

	return err
}

type NullableJarAttributes struct {
	value *JarAttributes
	isSet bool
}

func (v NullableJarAttributes) Get() *JarAttributes {
	return v.value
}

func (v *NullableJarAttributes) Set(val *JarAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableJarAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableJarAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJarAttributes(val *JarAttributes) *NullableJarAttributes {
	return &NullableJarAttributes{value: val, isSet: true}
}

func (v NullableJarAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJarAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


