/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PointCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointCreateData{}

// PointCreateData struct for PointCreateData
type PointCreateData struct {
	// point id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes PointCreateDataAttributes `json:"attributes"`
}

type _PointCreateData PointCreateData

// NewPointCreateData instantiates a new PointCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointCreateData(id string, type_ string, attributes PointCreateDataAttributes) *PointCreateData {
	this := PointCreateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewPointCreateDataWithDefaults instantiates a new PointCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointCreateDataWithDefaults() *PointCreateData {
	this := PointCreateData{}
	return &this
}

// GetId returns the Id field value
func (o *PointCreateData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PointCreateData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PointCreateData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PointCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PointCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PointCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PointCreateData) GetAttributes() PointCreateDataAttributes {
	if o == nil {
		var ret PointCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PointCreateData) GetAttributesOk() (*PointCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PointCreateData) SetAttributes(v PointCreateDataAttributes) {
	o.Attributes = v
}

func (o PointCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *PointCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointCreateData := _PointCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPointCreateData)

	if err != nil {
		return err
	}

	*o = PointCreateData(varPointCreateData)

	return err
}

type NullablePointCreateData struct {
	value *PointCreateData
	isSet bool
}

func (v NullablePointCreateData) Get() *PointCreateData {
	return v.value
}

func (v *NullablePointCreateData) Set(val *PointCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullablePointCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullablePointCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointCreateData(val *PointCreateData) *NullablePointCreateData {
	return &NullablePointCreateData{value: val, isSet: true}
}

func (v NullablePointCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


