/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JarUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JarUpdate{}

// JarUpdate struct for JarUpdate
type JarUpdate struct {
	Data JarUpdateData `json:"data"`
}

type _JarUpdate JarUpdate

// NewJarUpdate instantiates a new JarUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJarUpdate(data JarUpdateData) *JarUpdate {
	this := JarUpdate{}
	this.Data = data
	return &this
}

// NewJarUpdateWithDefaults instantiates a new JarUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJarUpdateWithDefaults() *JarUpdate {
	this := JarUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *JarUpdate) GetData() JarUpdateData {
	if o == nil {
		var ret JarUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *JarUpdate) GetDataOk() (*JarUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *JarUpdate) SetData(v JarUpdateData) {
	o.Data = v
}

func (o JarUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JarUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *JarUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJarUpdate := _JarUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJarUpdate)

	if err != nil {
		return err
	}

	*o = JarUpdate(varJarUpdate)

	return err
}

type NullableJarUpdate struct {
	value *JarUpdate
	isSet bool
}

func (v NullableJarUpdate) Get() *JarUpdate {
	return v.value
}

func (v *NullableJarUpdate) Set(val *JarUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableJarUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableJarUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJarUpdate(val *JarUpdate) *NullableJarUpdate {
	return &NullableJarUpdate{value: val, isSet: true}
}

func (v NullableJarUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJarUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


