/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the PointUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointUpdateDataAttributes{}

// PointUpdateDataAttributes struct for PointUpdateDataAttributes
type PointUpdateDataAttributes struct {
	// level of point
	Level *int32 `json:"level,omitempty"`
	// title of point
	Title *string `json:"title,omitempty"`
	// description of point
	Desc *string `json:"desc,omitempty"`
	// local cost
	LocalCost *int32 `json:"local_cost,omitempty"`
	// status of point
	Status *string `json:"status,omitempty"`
}

// NewPointUpdateDataAttributes instantiates a new PointUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointUpdateDataAttributes() *PointUpdateDataAttributes {
	this := PointUpdateDataAttributes{}
	return &this
}

// NewPointUpdateDataAttributesWithDefaults instantiates a new PointUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointUpdateDataAttributesWithDefaults() *PointUpdateDataAttributes {
	this := PointUpdateDataAttributes{}
	return &this
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *PointUpdateDataAttributes) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUpdateDataAttributes) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *PointUpdateDataAttributes) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *PointUpdateDataAttributes) SetLevel(v int32) {
	o.Level = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PointUpdateDataAttributes) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUpdateDataAttributes) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PointUpdateDataAttributes) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PointUpdateDataAttributes) SetTitle(v string) {
	o.Title = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *PointUpdateDataAttributes) GetDesc() string {
	if o == nil || IsNil(o.Desc) {
		var ret string
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUpdateDataAttributes) GetDescOk() (*string, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *PointUpdateDataAttributes) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given string and assigns it to the Desc field.
func (o *PointUpdateDataAttributes) SetDesc(v string) {
	o.Desc = &v
}

// GetLocalCost returns the LocalCost field value if set, zero value otherwise.
func (o *PointUpdateDataAttributes) GetLocalCost() int32 {
	if o == nil || IsNil(o.LocalCost) {
		var ret int32
		return ret
	}
	return *o.LocalCost
}

// GetLocalCostOk returns a tuple with the LocalCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUpdateDataAttributes) GetLocalCostOk() (*int32, bool) {
	if o == nil || IsNil(o.LocalCost) {
		return nil, false
	}
	return o.LocalCost, true
}

// HasLocalCost returns a boolean if a field has been set.
func (o *PointUpdateDataAttributes) HasLocalCost() bool {
	if o != nil && !IsNil(o.LocalCost) {
		return true
	}

	return false
}

// SetLocalCost gets a reference to the given int32 and assigns it to the LocalCost field.
func (o *PointUpdateDataAttributes) SetLocalCost(v int32) {
	o.LocalCost = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PointUpdateDataAttributes) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUpdateDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PointUpdateDataAttributes) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PointUpdateDataAttributes) SetStatus(v string) {
	o.Status = &v
}

func (o PointUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	if !IsNil(o.LocalCost) {
		toSerialize["local_cost"] = o.LocalCost
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullablePointUpdateDataAttributes struct {
	value *PointUpdateDataAttributes
	isSet bool
}

func (v NullablePointUpdateDataAttributes) Get() *PointUpdateDataAttributes {
	return v.value
}

func (v *NullablePointUpdateDataAttributes) Set(val *PointUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullablePointUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullablePointUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointUpdateDataAttributes(val *PointUpdateDataAttributes) *NullablePointUpdateDataAttributes {
	return &NullablePointUpdateDataAttributes{value: val, isSet: true}
}

func (v NullablePointUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


