/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiativeTagData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeTagData{}

// InitiativeTagData struct for InitiativeTagData
type InitiativeTagData struct {
	// tag id
	Id string `json:"id"`
	// tag name
	Name string `json:"name"`
	// tag weight
	Weight int32 `json:"weight"`
}

type _InitiativeTagData InitiativeTagData

// NewInitiativeTagData instantiates a new InitiativeTagData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeTagData(id string, name string, weight int32) *InitiativeTagData {
	this := InitiativeTagData{}
	this.Id = id
	this.Name = name
	this.Weight = weight
	return &this
}

// NewInitiativeTagDataWithDefaults instantiates a new InitiativeTagData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeTagDataWithDefaults() *InitiativeTagData {
	this := InitiativeTagData{}
	return &this
}

// GetId returns the Id field value
func (o *InitiativeTagData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InitiativeTagData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InitiativeTagData) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *InitiativeTagData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InitiativeTagData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InitiativeTagData) SetName(v string) {
	o.Name = v
}

// GetWeight returns the Weight field value
func (o *InitiativeTagData) GetWeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *InitiativeTagData) GetWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *InitiativeTagData) SetWeight(v int32) {
	o.Weight = v
}

func (o InitiativeTagData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeTagData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["weight"] = o.Weight
	return toSerialize, nil
}

func (o *InitiativeTagData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"weight",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiativeTagData := _InitiativeTagData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiativeTagData)

	if err != nil {
		return err
	}

	*o = InitiativeTagData(varInitiativeTagData)

	return err
}

type NullableInitiativeTagData struct {
	value *InitiativeTagData
	isSet bool
}

func (v NullableInitiativeTagData) Get() *InitiativeTagData {
	return v.value
}

func (v *NullableInitiativeTagData) Set(val *InitiativeTagData) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeTagData) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeTagData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeTagData(val *InitiativeTagData) *NullableInitiativeTagData {
	return &NullableInitiativeTagData{value: val, isSet: true}
}

func (v NullableInitiativeTagData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeTagData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


