/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiativeCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeCreate{}

// InitiativeCreate struct for InitiativeCreate
type InitiativeCreate struct {
	Data InitiativeCreateData `json:"data"`
}

type _InitiativeCreate InitiativeCreate

// NewInitiativeCreate instantiates a new InitiativeCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeCreate(data InitiativeCreateData) *InitiativeCreate {
	this := InitiativeCreate{}
	this.Data = data
	return &this
}

// NewInitiativeCreateWithDefaults instantiates a new InitiativeCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeCreateWithDefaults() *InitiativeCreate {
	this := InitiativeCreate{}
	return &this
}

// GetData returns the Data field value
func (o *InitiativeCreate) GetData() InitiativeCreateData {
	if o == nil {
		var ret InitiativeCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InitiativeCreate) GetDataOk() (*InitiativeCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *InitiativeCreate) SetData(v InitiativeCreateData) {
	o.Data = v
}

func (o InitiativeCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *InitiativeCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiativeCreate := _InitiativeCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiativeCreate)

	if err != nil {
		return err
	}

	*o = InitiativeCreate(varInitiativeCreate)

	return err
}

type NullableInitiativeCreate struct {
	value *InitiativeCreate
	isSet bool
}

func (v NullableInitiativeCreate) Get() *InitiativeCreate {
	return v.value
}

func (v *NullableInitiativeCreate) Set(val *InitiativeCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeCreate(val *InitiativeCreate) *NullableInitiativeCreate {
	return &NullableInitiativeCreate{value: val, isSet: true}
}

func (v NullableInitiativeCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


