/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LinksDirectPagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinksDirectPagination{}

// LinksDirectPagination struct for LinksDirectPagination
type LinksDirectPagination struct {
	Links LinksDirectPaginationLinks `json:"links"`
}

type _LinksDirectPagination LinksDirectPagination

// NewLinksDirectPagination instantiates a new LinksDirectPagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinksDirectPagination(links LinksDirectPaginationLinks) *LinksDirectPagination {
	this := LinksDirectPagination{}
	this.Links = links
	return &this
}

// NewLinksDirectPaginationWithDefaults instantiates a new LinksDirectPagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinksDirectPaginationWithDefaults() *LinksDirectPagination {
	this := LinksDirectPagination{}
	return &this
}

// GetLinks returns the Links field value
func (o *LinksDirectPagination) GetLinks() LinksDirectPaginationLinks {
	if o == nil {
		var ret LinksDirectPaginationLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *LinksDirectPagination) GetLinksOk() (*LinksDirectPaginationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *LinksDirectPagination) SetLinks(v LinksDirectPaginationLinks) {
	o.Links = v
}

func (o LinksDirectPagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinksDirectPagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *LinksDirectPagination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinksDirectPagination := _LinksDirectPagination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinksDirectPagination)

	if err != nil {
		return err
	}

	*o = LinksDirectPagination(varLinksDirectPagination)

	return err
}

type NullableLinksDirectPagination struct {
	value *LinksDirectPagination
	isSet bool
}

func (v NullableLinksDirectPagination) Get() *LinksDirectPagination {
	return v.value
}

func (v *NullableLinksDirectPagination) Set(val *LinksDirectPagination) {
	v.value = val
	v.isSet = true
}

func (v NullableLinksDirectPagination) IsSet() bool {
	return v.isSet
}

func (v *NullableLinksDirectPagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinksDirectPagination(val *LinksDirectPagination) *NullableLinksDirectPagination {
	return &NullableLinksDirectPagination{value: val, isSet: true}
}

func (v NullableLinksDirectPagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinksDirectPagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


