/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Jar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Jar{}

// Jar struct for Jar
type Jar struct {
	Data JarData `json:"data"`
}

type _Jar Jar

// NewJar instantiates a new Jar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJar(data JarData) *Jar {
	this := Jar{}
	this.Data = data
	return &this
}

// NewJarWithDefaults instantiates a new Jar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJarWithDefaults() *Jar {
	this := Jar{}
	return &this
}

// GetData returns the Data field value
func (o *Jar) GetData() JarData {
	if o == nil {
		var ret JarData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Jar) GetDataOk() (*JarData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Jar) SetData(v JarData) {
	o.Data = v
}

func (o Jar) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Jar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *Jar) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJar := _Jar{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJar)

	if err != nil {
		return err
	}

	*o = Jar(varJar)

	return err
}

type NullableJar struct {
	value *Jar
	isSet bool
}

func (v NullableJar) Get() *Jar {
	return v.value
}

func (v *NullableJar) Set(val *Jar) {
	v.value = val
	v.isSet = true
}

func (v NullableJar) IsSet() bool {
	return v.isSet
}

func (v *NullableJar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJar(val *Jar) *NullableJar {
	return &NullableJar{value: val, isSet: true}
}

func (v NullableJar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


