/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiativeUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeUpdateDataAttributes{}

// InitiativeUpdateDataAttributes struct for InitiativeUpdateDataAttributes
type InitiativeUpdateDataAttributes struct {
	// name of initiative
	Name string `json:"name"`
	// description of initiative
	Desc string `json:"desc"`
	// goal of initiative
	Goal string `json:"goal"`
	// location of initiative
	Location *string `json:"location,omitempty"`
	// status of initiative
	Status string `json:"status"`
}

type _InitiativeUpdateDataAttributes InitiativeUpdateDataAttributes

// NewInitiativeUpdateDataAttributes instantiates a new InitiativeUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeUpdateDataAttributes(name string, desc string, goal string, status string) *InitiativeUpdateDataAttributes {
	this := InitiativeUpdateDataAttributes{}
	this.Name = name
	this.Desc = desc
	this.Goal = goal
	this.Status = status
	return &this
}

// NewInitiativeUpdateDataAttributesWithDefaults instantiates a new InitiativeUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeUpdateDataAttributesWithDefaults() *InitiativeUpdateDataAttributes {
	this := InitiativeUpdateDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *InitiativeUpdateDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InitiativeUpdateDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *InitiativeUpdateDataAttributes) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *InitiativeUpdateDataAttributes) SetDesc(v string) {
	o.Desc = v
}

// GetGoal returns the Goal field value
func (o *InitiativeUpdateDataAttributes) GetGoal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Goal
}

// GetGoalOk returns a tuple with the Goal field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetGoalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Goal, true
}

// SetGoal sets field value
func (o *InitiativeUpdateDataAttributes) SetGoal(v string) {
	o.Goal = v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *InitiativeUpdateDataAttributes) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *InitiativeUpdateDataAttributes) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *InitiativeUpdateDataAttributes) SetLocation(v string) {
	o.Location = &v
}

// GetStatus returns the Status field value
func (o *InitiativeUpdateDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InitiativeUpdateDataAttributes) SetStatus(v string) {
	o.Status = v
}

func (o InitiativeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["goal"] = o.Goal
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *InitiativeUpdateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"goal",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiativeUpdateDataAttributes := _InitiativeUpdateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiativeUpdateDataAttributes)

	if err != nil {
		return err
	}

	*o = InitiativeUpdateDataAttributes(varInitiativeUpdateDataAttributes)

	return err
}

type NullableInitiativeUpdateDataAttributes struct {
	value *InitiativeUpdateDataAttributes
	isSet bool
}

func (v NullableInitiativeUpdateDataAttributes) Get() *InitiativeUpdateDataAttributes {
	return v.value
}

func (v *NullableInitiativeUpdateDataAttributes) Set(val *InitiativeUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeUpdateDataAttributes(val *InitiativeUpdateDataAttributes) *NullableInitiativeUpdateDataAttributes {
	return &NullableInitiativeUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableInitiativeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


