/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Initiative type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Initiative{}

// Initiative struct for Initiative
type Initiative struct {
	Data InitiativeData `json:"data"`
	Included InitiativeIncluded `json:"included"`
}

type _Initiative Initiative

// NewInitiative instantiates a new Initiative object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiative(data InitiativeData, included InitiativeIncluded) *Initiative {
	this := Initiative{}
	this.Data = data
	this.Included = included
	return &this
}

// NewInitiativeWithDefaults instantiates a new Initiative object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeWithDefaults() *Initiative {
	this := Initiative{}
	return &this
}

// GetData returns the Data field value
func (o *Initiative) GetData() InitiativeData {
	if o == nil {
		var ret InitiativeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Initiative) GetDataOk() (*InitiativeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Initiative) SetData(v InitiativeData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *Initiative) GetIncluded() InitiativeIncluded {
	if o == nil {
		var ret InitiativeIncluded
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *Initiative) GetIncludedOk() (*InitiativeIncluded, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Included, true
}

// SetIncluded sets field value
func (o *Initiative) SetIncluded(v InitiativeIncluded) {
	o.Included = v
}

func (o Initiative) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Initiative) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *Initiative) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiative := _Initiative{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiative)

	if err != nil {
		return err
	}

	*o = Initiative(varInitiative)

	return err
}

type NullableInitiative struct {
	value *Initiative
	isSet bool
}

func (v NullableInitiative) Get() *Initiative {
	return v.value
}

func (v *NullableInitiative) Set(val *Initiative) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiative) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiative) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiative(val *Initiative) *NullableInitiative {
	return &NullableInitiative{value: val, isSet: true}
}

func (v NullableInitiative) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiative) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


