/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PointCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointCreate{}

// PointCreate struct for PointCreate
type PointCreate struct {
	Data PointCreateData `json:"data"`
}

type _PointCreate PointCreate

// NewPointCreate instantiates a new PointCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointCreate(data PointCreateData) *PointCreate {
	this := PointCreate{}
	this.Data = data
	return &this
}

// NewPointCreateWithDefaults instantiates a new PointCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointCreateWithDefaults() *PointCreate {
	this := PointCreate{}
	return &this
}

// GetData returns the Data field value
func (o *PointCreate) GetData() PointCreateData {
	if o == nil {
		var ret PointCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PointCreate) GetDataOk() (*PointCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PointCreate) SetData(v PointCreateData) {
	o.Data = v
}

func (o PointCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PointCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointCreate := _PointCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPointCreate)

	if err != nil {
		return err
	}

	*o = PointCreate(varPointCreate)

	return err
}

type NullablePointCreate struct {
	value *PointCreate
	isSet bool
}

func (v NullablePointCreate) Get() *PointCreate {
	return v.value
}

func (v *NullablePointCreate) Set(val *PointCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePointCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePointCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointCreate(val *PointCreate) *NullablePointCreate {
	return &NullablePointCreate{value: val, isSet: true}
}

func (v NullablePointCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


