/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddOrgMemberData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddOrgMemberData{}

// AddOrgMemberData struct for AddOrgMemberData
type AddOrgMemberData struct {
	Type string `json:"type"`
	Attributes AddOrgMemberDataAttributes `json:"attributes"`
}

type _AddOrgMemberData AddOrgMemberData

// NewAddOrgMemberData instantiates a new AddOrgMemberData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddOrgMemberData(type_ string, attributes AddOrgMemberDataAttributes) *AddOrgMemberData {
	this := AddOrgMemberData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAddOrgMemberDataWithDefaults instantiates a new AddOrgMemberData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddOrgMemberDataWithDefaults() *AddOrgMemberData {
	this := AddOrgMemberData{}
	return &this
}

// GetType returns the Type field value
func (o *AddOrgMemberData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AddOrgMemberData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AddOrgMemberData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AddOrgMemberData) GetAttributes() AddOrgMemberDataAttributes {
	if o == nil {
		var ret AddOrgMemberDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AddOrgMemberData) GetAttributesOk() (*AddOrgMemberDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AddOrgMemberData) SetAttributes(v AddOrgMemberDataAttributes) {
	o.Attributes = v
}

func (o AddOrgMemberData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddOrgMemberData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AddOrgMemberData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddOrgMemberData := _AddOrgMemberData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddOrgMemberData)

	if err != nil {
		return err
	}

	*o = AddOrgMemberData(varAddOrgMemberData)

	return err
}

type NullableAddOrgMemberData struct {
	value *AddOrgMemberData
	isSet bool
}

func (v NullableAddOrgMemberData) Get() *AddOrgMemberData {
	return v.value
}

func (v *NullableAddOrgMemberData) Set(val *AddOrgMemberData) {
	v.value = val
	v.isSet = true
}

func (v NullableAddOrgMemberData) IsSet() bool {
	return v.isSet
}

func (v *NullableAddOrgMemberData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddOrgMemberData(val *AddOrgMemberData) *NullableAddOrgMemberData {
	return &NullableAddOrgMemberData{value: val, isSet: true}
}

func (v NullableAddOrgMemberData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddOrgMemberData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


