/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PointData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointData{}

// PointData struct for PointData
type PointData struct {
	// point id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes PointAttributes `json:"attributes"`
	Relationships PointDataRelationships `json:"relationships"`
}

type _PointData PointData

// NewPointData instantiates a new PointData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointData(id string, type_ string, attributes PointAttributes, relationships PointDataRelationships) *PointData {
	this := PointData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewPointDataWithDefaults instantiates a new PointData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointDataWithDefaults() *PointData {
	this := PointData{}
	return &this
}

// GetId returns the Id field value
func (o *PointData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PointData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PointData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PointData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PointData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PointData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PointData) GetAttributes() PointAttributes {
	if o == nil {
		var ret PointAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PointData) GetAttributesOk() (*PointAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PointData) SetAttributes(v PointAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *PointData) GetRelationships() PointDataRelationships {
	if o == nil {
		var ret PointDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *PointData) GetRelationshipsOk() (*PointDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *PointData) SetRelationships(v PointDataRelationships) {
	o.Relationships = v
}

func (o PointData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *PointData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointData := _PointData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPointData)

	if err != nil {
		return err
	}

	*o = PointData(varPointData)

	return err
}

type NullablePointData struct {
	value *PointData
	isSet bool
}

func (v NullablePointData) Get() *PointData {
	return v.value
}

func (v *NullablePointData) Set(val *PointData) {
	v.value = val
	v.isSet = true
}

func (v NullablePointData) IsSet() bool {
	return v.isSet
}

func (v *NullablePointData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointData(val *PointData) *NullablePointData {
	return &NullablePointData{value: val, isSet: true}
}

func (v NullablePointData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


