/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LinkSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkSelf{}

// LinkSelf struct for LinkSelf
type LinkSelf struct {
	// Link to participants
	Self string `json:"self"`
}

type _LinkSelf LinkSelf

// NewLinkSelf instantiates a new LinkSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkSelf(self string) *LinkSelf {
	this := LinkSelf{}
	this.Self = self
	return &this
}

// NewLinkSelfWithDefaults instantiates a new LinkSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkSelfWithDefaults() *LinkSelf {
	this := LinkSelf{}
	return &this
}

// GetSelf returns the Self field value
func (o *LinkSelf) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *LinkSelf) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *LinkSelf) SetSelf(v string) {
	o.Self = v
}

func (o LinkSelf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	return toSerialize, nil
}

func (o *LinkSelf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkSelf := _LinkSelf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinkSelf)

	if err != nil {
		return err
	}

	*o = LinkSelf(varLinkSelf)

	return err
}

type NullableLinkSelf struct {
	value *LinkSelf
	isSet bool
}

func (v NullableLinkSelf) Get() *LinkSelf {
	return v.value
}

func (v *NullableLinkSelf) Set(val *LinkSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkSelf(val *LinkSelf) *NullableLinkSelf {
	return &NullableLinkSelf{value: val, isSet: true}
}

func (v NullableLinkSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


