/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PointUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointUpdateData{}

// PointUpdateData struct for PointUpdateData
type PointUpdateData struct {
	Type string `json:"type"`
	Attributes PointUpdateDataAttributes `json:"attributes"`
}

type _PointUpdateData PointUpdateData

// NewPointUpdateData instantiates a new PointUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointUpdateData(type_ string, attributes PointUpdateDataAttributes) *PointUpdateData {
	this := PointUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewPointUpdateDataWithDefaults instantiates a new PointUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointUpdateDataWithDefaults() *PointUpdateData {
	this := PointUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *PointUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PointUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PointUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PointUpdateData) GetAttributes() PointUpdateDataAttributes {
	if o == nil {
		var ret PointUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PointUpdateData) GetAttributesOk() (*PointUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PointUpdateData) SetAttributes(v PointUpdateDataAttributes) {
	o.Attributes = v
}

func (o PointUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *PointUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointUpdateData := _PointUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPointUpdateData)

	if err != nil {
		return err
	}

	*o = PointUpdateData(varPointUpdateData)

	return err
}

type NullablePointUpdateData struct {
	value *PointUpdateData
	isSet bool
}

func (v NullablePointUpdateData) Get() *PointUpdateData {
	return v.value
}

func (v *NullablePointUpdateData) Set(val *PointUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullablePointUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullablePointUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointUpdateData(val *PointUpdateData) *NullablePointUpdateData {
	return &NullablePointUpdateData{value: val, isSet: true}
}

func (v NullablePointUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


