/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddOrgMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddOrgMember{}

// AddOrgMember struct for AddOrgMember
type AddOrgMember struct {
	Data AddOrgMemberData `json:"data"`
}

type _AddOrgMember AddOrgMember

// NewAddOrgMember instantiates a new AddOrgMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddOrgMember(data AddOrgMemberData) *AddOrgMember {
	this := AddOrgMember{}
	this.Data = data
	return &this
}

// NewAddOrgMemberWithDefaults instantiates a new AddOrgMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddOrgMemberWithDefaults() *AddOrgMember {
	this := AddOrgMember{}
	return &this
}

// GetData returns the Data field value
func (o *AddOrgMember) GetData() AddOrgMemberData {
	if o == nil {
		var ret AddOrgMemberData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AddOrgMember) GetDataOk() (*AddOrgMemberData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AddOrgMember) SetData(v AddOrgMemberData) {
	o.Data = v
}

func (o AddOrgMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddOrgMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AddOrgMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddOrgMember := _AddOrgMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddOrgMember)

	if err != nil {
		return err
	}

	*o = AddOrgMember(varAddOrgMember)

	return err
}

type NullableAddOrgMember struct {
	value *AddOrgMember
	isSet bool
}

func (v NullableAddOrgMember) Get() *AddOrgMember {
	return v.value
}

func (v *NullableAddOrgMember) Set(val *AddOrgMember) {
	v.value = val
	v.isSet = true
}

func (v NullableAddOrgMember) IsSet() bool {
	return v.isSet
}

func (v *NullableAddOrgMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddOrgMember(val *AddOrgMember) *NullableAddOrgMember {
	return &NullableAddOrgMember{value: val, isSet: true}
}

func (v NullableAddOrgMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddOrgMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


