/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PointUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointUpdate{}

// PointUpdate struct for PointUpdate
type PointUpdate struct {
	Data PointUpdateData `json:"data"`
}

type _PointUpdate PointUpdate

// NewPointUpdate instantiates a new PointUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointUpdate(data PointUpdateData) *PointUpdate {
	this := PointUpdate{}
	this.Data = data
	return &this
}

// NewPointUpdateWithDefaults instantiates a new PointUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointUpdateWithDefaults() *PointUpdate {
	this := PointUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *PointUpdate) GetData() PointUpdateData {
	if o == nil {
		var ret PointUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PointUpdate) GetDataOk() (*PointUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PointUpdate) SetData(v PointUpdateData) {
	o.Data = v
}

func (o PointUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PointUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointUpdate := _PointUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPointUpdate)

	if err != nil {
		return err
	}

	*o = PointUpdate(varPointUpdate)

	return err
}

type NullablePointUpdate struct {
	value *PointUpdate
	isSet bool
}

func (v NullablePointUpdate) Get() *PointUpdate {
	return v.value
}

func (v *NullablePointUpdate) Set(val *PointUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePointUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePointUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointUpdate(val *PointUpdate) *NullablePointUpdate {
	return &NullablePointUpdate{value: val, isSet: true}
}

func (v NullablePointUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


