/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JarData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JarData{}

// JarData struct for JarData
type JarData struct {
	// point id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes JarAttributes `json:"attributes"`
	Relationships *JarDataRelationships `json:"relationships,omitempty"`
}

type _JarData JarData

// NewJarData instantiates a new JarData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJarData(id string, type_ string, attributes JarAttributes) *JarData {
	this := JarData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewJarDataWithDefaults instantiates a new JarData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJarDataWithDefaults() *JarData {
	this := JarData{}
	return &this
}

// GetId returns the Id field value
func (o *JarData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JarData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JarData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *JarData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JarData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JarData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *JarData) GetAttributes() JarAttributes {
	if o == nil {
		var ret JarAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *JarData) GetAttributesOk() (*JarAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *JarData) SetAttributes(v JarAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *JarData) GetRelationships() JarDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret JarDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JarData) GetRelationshipsOk() (*JarDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *JarData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given JarDataRelationships and assigns it to the Relationships field.
func (o *JarData) SetRelationships(v JarDataRelationships) {
	o.Relationships = &v
}

func (o JarData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JarData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *JarData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJarData := _JarData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJarData)

	if err != nil {
		return err
	}

	*o = JarData(varJarData)

	return err
}

type NullableJarData struct {
	value *JarData
	isSet bool
}

func (v NullableJarData) Get() *JarData {
	return v.value
}

func (v *NullableJarData) Set(val *JarData) {
	v.value = val
	v.isSet = true
}

func (v NullableJarData) IsSet() bool {
	return v.isSet
}

func (v *NullableJarData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJarData(val *JarData) *NullableJarData {
	return &NullableJarData{value: val, isSet: true}
}

func (v NullableJarData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJarData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


