/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiativeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeUpdate{}

// InitiativeUpdate struct for InitiativeUpdate
type InitiativeUpdate struct {
	Data InitiativeUpdateData `json:"data"`
}

type _InitiativeUpdate InitiativeUpdate

// NewInitiativeUpdate instantiates a new InitiativeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeUpdate(data InitiativeUpdateData) *InitiativeUpdate {
	this := InitiativeUpdate{}
	this.Data = data
	return &this
}

// NewInitiativeUpdateWithDefaults instantiates a new InitiativeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeUpdateWithDefaults() *InitiativeUpdate {
	this := InitiativeUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *InitiativeUpdate) GetData() InitiativeUpdateData {
	if o == nil {
		var ret InitiativeUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetDataOk() (*InitiativeUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *InitiativeUpdate) SetData(v InitiativeUpdateData) {
	o.Data = v
}

func (o InitiativeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *InitiativeUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiativeUpdate := _InitiativeUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiativeUpdate)

	if err != nil {
		return err
	}

	*o = InitiativeUpdate(varInitiativeUpdate)

	return err
}

type NullableInitiativeUpdate struct {
	value *InitiativeUpdate
	isSet bool
}

func (v NullableInitiativeUpdate) Get() *InitiativeUpdate {
	return v.value
}

func (v *NullableInitiativeUpdate) Set(val *InitiativeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeUpdate(val *InitiativeUpdate) *NullableInitiativeUpdate {
	return &NullableInitiativeUpdate{value: val, isSet: true}
}

func (v NullableInitiativeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


