/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiativeCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeCreateData{}

// InitiativeCreateData struct for InitiativeCreateData
type InitiativeCreateData struct {
	Type string `json:"type"`
	Attributes InitiativeCreateDataAttributes `json:"attributes"`
}

type _InitiativeCreateData InitiativeCreateData

// NewInitiativeCreateData instantiates a new InitiativeCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeCreateData(type_ string, attributes InitiativeCreateDataAttributes) *InitiativeCreateData {
	this := InitiativeCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewInitiativeCreateDataWithDefaults instantiates a new InitiativeCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeCreateDataWithDefaults() *InitiativeCreateData {
	this := InitiativeCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *InitiativeCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InitiativeCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InitiativeCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *InitiativeCreateData) GetAttributes() InitiativeCreateDataAttributes {
	if o == nil {
		var ret InitiativeCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *InitiativeCreateData) GetAttributesOk() (*InitiativeCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *InitiativeCreateData) SetAttributes(v InitiativeCreateDataAttributes) {
	o.Attributes = v
}

func (o InitiativeCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *InitiativeCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiativeCreateData := _InitiativeCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiativeCreateData)

	if err != nil {
		return err
	}

	*o = InitiativeCreateData(varInitiativeCreateData)

	return err
}

type NullableInitiativeCreateData struct {
	value *InitiativeCreateData
	isSet bool
}

func (v NullableInitiativeCreateData) Get() *InitiativeCreateData {
	return v.value
}

func (v *NullableInitiativeCreateData) Set(val *InitiativeCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeCreateData(val *InitiativeCreateData) *NullableInitiativeCreateData {
	return &NullableInitiativeCreateData{value: val, isSet: true}
}

func (v NullableInitiativeCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


