/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InitiativeUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeUpdateData{}

// InitiativeUpdateData struct for InitiativeUpdateData
type InitiativeUpdateData struct {
	// initiative id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes InitiativeUpdateDataAttributes `json:"attributes"`
}

type _InitiativeUpdateData InitiativeUpdateData

// NewInitiativeUpdateData instantiates a new InitiativeUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeUpdateData(id string, type_ string, attributes InitiativeUpdateDataAttributes) *InitiativeUpdateData {
	this := InitiativeUpdateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewInitiativeUpdateDataWithDefaults instantiates a new InitiativeUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeUpdateDataWithDefaults() *InitiativeUpdateData {
	this := InitiativeUpdateData{}
	return &this
}

// GetId returns the Id field value
func (o *InitiativeUpdateData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InitiativeUpdateData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *InitiativeUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InitiativeUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *InitiativeUpdateData) GetAttributes() InitiativeUpdateDataAttributes {
	if o == nil {
		var ret InitiativeUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateData) GetAttributesOk() (*InitiativeUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *InitiativeUpdateData) SetAttributes(v InitiativeUpdateDataAttributes) {
	o.Attributes = v
}

func (o InitiativeUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *InitiativeUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiativeUpdateData := _InitiativeUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInitiativeUpdateData)

	if err != nil {
		return err
	}

	*o = InitiativeUpdateData(varInitiativeUpdateData)

	return err
}

type NullableInitiativeUpdateData struct {
	value *InitiativeUpdateData
	isSet bool
}

func (v NullableInitiativeUpdateData) Get() *InitiativeUpdateData {
	return v.value
}

func (v *NullableInitiativeUpdateData) Set(val *InitiativeUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeUpdateData(val *InitiativeUpdateData) *NullableInitiativeUpdateData {
	return &NullableInitiativeUpdateData{value: val, isSet: true}
}

func (v NullableInitiativeUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


