/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WalletsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletsUpdate{}

// WalletsUpdate struct for WalletsUpdate
type WalletsUpdate struct {
	Data WalletsUpdateData `json:"data"`
}

type _WalletsUpdate WalletsUpdate

// NewWalletsUpdate instantiates a new WalletsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletsUpdate(data WalletsUpdateData) *WalletsUpdate {
	this := WalletsUpdate{}
	this.Data = data
	return &this
}

// NewWalletsUpdateWithDefaults instantiates a new WalletsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletsUpdateWithDefaults() *WalletsUpdate {
	this := WalletsUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *WalletsUpdate) GetData() WalletsUpdateData {
	if o == nil {
		var ret WalletsUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WalletsUpdate) GetDataOk() (*WalletsUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *WalletsUpdate) SetData(v WalletsUpdateData) {
	o.Data = v
}

func (o WalletsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *WalletsUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletsUpdate := _WalletsUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWalletsUpdate)

	if err != nil {
		return err
	}

	*o = WalletsUpdate(varWalletsUpdate)

	return err
}

type NullableWalletsUpdate struct {
	value *WalletsUpdate
	isSet bool
}

func (v NullableWalletsUpdate) Get() *WalletsUpdate {
	return v.value
}

func (v *NullableWalletsUpdate) Set(val *WalletsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletsUpdate(val *WalletsUpdate) *NullableWalletsUpdate {
	return &NullableWalletsUpdate{value: val, isSet: true}
}

func (v NullableWalletsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


