/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the InitiativeUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeUpdateDataAttributes{}

// InitiativeUpdateDataAttributes struct for InitiativeUpdateDataAttributes
type InitiativeUpdateDataAttributes struct {
	// name of initiative
	Name *string `json:"name,omitempty"`
	// description of initiative
	Desc *string `json:"desc,omitempty"`
	// goal of initiative
	Goal *string `json:"goal,omitempty"`
	// location of initiative
	Location *string `json:"location,omitempty"`
	// status of initiative
	Status *string `json:"status,omitempty"`
}

// NewInitiativeUpdateDataAttributes instantiates a new InitiativeUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeUpdateDataAttributes() *InitiativeUpdateDataAttributes {
	this := InitiativeUpdateDataAttributes{}
	return &this
}

// NewInitiativeUpdateDataAttributesWithDefaults instantiates a new InitiativeUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeUpdateDataAttributesWithDefaults() *InitiativeUpdateDataAttributes {
	this := InitiativeUpdateDataAttributes{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InitiativeUpdateDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InitiativeUpdateDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InitiativeUpdateDataAttributes) SetName(v string) {
	o.Name = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *InitiativeUpdateDataAttributes) GetDesc() string {
	if o == nil || IsNil(o.Desc) {
		var ret string
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetDescOk() (*string, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *InitiativeUpdateDataAttributes) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given string and assigns it to the Desc field.
func (o *InitiativeUpdateDataAttributes) SetDesc(v string) {
	o.Desc = &v
}

// GetGoal returns the Goal field value if set, zero value otherwise.
func (o *InitiativeUpdateDataAttributes) GetGoal() string {
	if o == nil || IsNil(o.Goal) {
		var ret string
		return ret
	}
	return *o.Goal
}

// GetGoalOk returns a tuple with the Goal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetGoalOk() (*string, bool) {
	if o == nil || IsNil(o.Goal) {
		return nil, false
	}
	return o.Goal, true
}

// HasGoal returns a boolean if a field has been set.
func (o *InitiativeUpdateDataAttributes) HasGoal() bool {
	if o != nil && !IsNil(o.Goal) {
		return true
	}

	return false
}

// SetGoal gets a reference to the given string and assigns it to the Goal field.
func (o *InitiativeUpdateDataAttributes) SetGoal(v string) {
	o.Goal = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *InitiativeUpdateDataAttributes) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *InitiativeUpdateDataAttributes) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *InitiativeUpdateDataAttributes) SetLocation(v string) {
	o.Location = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InitiativeUpdateDataAttributes) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdateDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InitiativeUpdateDataAttributes) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *InitiativeUpdateDataAttributes) SetStatus(v string) {
	o.Status = &v
}

func (o InitiativeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	if !IsNil(o.Goal) {
		toSerialize["goal"] = o.Goal
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableInitiativeUpdateDataAttributes struct {
	value *InitiativeUpdateDataAttributes
	isSet bool
}

func (v NullableInitiativeUpdateDataAttributes) Get() *InitiativeUpdateDataAttributes {
	return v.value
}

func (v *NullableInitiativeUpdateDataAttributes) Set(val *InitiativeUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeUpdateDataAttributes(val *InitiativeUpdateDataAttributes) *NullableInitiativeUpdateDataAttributes {
	return &NullableInitiativeUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableInitiativeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


