/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LinkDirect type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkDirect{}

// LinkDirect struct for LinkDirect
type LinkDirect struct {
	// Link to chat
	Links string `json:"links"`
}

type _LinkDirect LinkDirect

// NewLinkDirect instantiates a new LinkDirect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkDirect(links string) *LinkDirect {
	this := LinkDirect{}
	this.Links = links
	return &this
}

// NewLinkDirectWithDefaults instantiates a new LinkDirect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkDirectWithDefaults() *LinkDirect {
	this := LinkDirect{}
	return &this
}

// GetLinks returns the Links field value
func (o *LinkDirect) GetLinks() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *LinkDirect) GetLinksOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *LinkDirect) SetLinks(v string) {
	o.Links = v
}

func (o LinkDirect) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkDirect) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *LinkDirect) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkDirect := _LinkDirect{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinkDirect)

	if err != nil {
		return err
	}

	*o = LinkDirect(varLinkDirect)

	return err
}

type NullableLinkDirect struct {
	value *LinkDirect
	isSet bool
}

func (v NullableLinkDirect) Get() *LinkDirect {
	return v.value
}

func (v *NullableLinkDirect) Set(val *LinkDirect) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkDirect) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkDirect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkDirect(val *LinkDirect) *NullableLinkDirect {
	return &NullableLinkDirect{value: val, isSet: true}
}

func (v NullableLinkDirect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkDirect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


