openapi: 3.0.3
info:
  description: example
  title: test
  version: 0.0.0
servers:
- url: /
paths:
  /test:
    post:
      operationId: test
      responses:
        "201":
          description: Ok
      summary: Test
components:
  schemas:
    Initiative:
      properties:
        data:
          $ref: '#/components/schemas/Initiative_data'
        included:
          $ref: '#/components/schemas/Initiative_included'
      required:
      - data
      type: object
    InitiativeCreate:
      properties:
        data:
          $ref: '#/components/schemas/InitiativeCreate_data'
      required:
      - data
      type: object
    InitiativeUpdate:
      properties:
        data:
          $ref: '#/components/schemas/InitiativeUpdate_data'
      required:
      - data
      - included
      type: object
    Wallets:
      properties:
        bank_account:
          $ref: '#/components/schemas/Wallets_bank_account'
        payment_system:
          $ref: '#/components/schemas/Wallets_payment_system'
        crypto_wallets:
          $ref: '#/components/schemas/Wallets_crypto_wallets'
      type: object
    WalletsUpdate:
      properties:
        data:
          $ref: '#/components/schemas/WalletsUpdate_data'
      required:
      - data
      type: object
    AddOrgMember:
      properties:
        data:
          $ref: '#/components/schemas/AddOrgMember_data'
      required:
      - data
      type: object
    LinkSelf:
      properties:
        self:
          description: Link to participants
          type: string
      required:
      - self
      type: object
    LinksDirect:
      properties:
        links:
          $ref: '#/components/schemas/LinksDirect_links'
        data:
          $ref: '#/components/schemas/LinksDirect_data'
      required:
      - links
      type: object
    LinksPagination:
      properties:
        previous:
          description: Link to the previous page
          type: string
        self:
          description: Link to the current page
          type: string
        next:
          description: Link to the next page
          type: string
      required:
      - next
      - previous
      - self
      type: object
    Initiative_data_attributes:
      properties:
        name:
          description: name of initiative
          type: string
        desc:
          description: description of initiative
          type: string
        goal:
          description: goal of initiative
          type: string
        verified:
          description: verified status
          type: boolean
        location:
          description: location of initiative
          type: string
        type:
          description: types of initiative
          type: string
        status:
          description: status of initiative
          type: string
        final_cost:
          description: final cost of initiative
          format: int64
          type: integer
        collected_sum:
          description: collected sum of initiative
          format: int64
          type: integer
        likes:
          description: likes of initiative
          format: int64
          type: integer
        reposts:
          description: reposts of initiative
          format: int64
          type: integer
        reports:
          description: reports of initiative
          format: int64
          type: integer
        start_at:
          description: start date of initiative
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        end_at:
          description: end date of initiative
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        updated_at:
          description: Initiative updated at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        closed_at:
          description: Initiative closed at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - desc
      - goal
      - likes
      - name
      - reports
      - reposts
      - status
      - type
      - verified
      type: object
    Initiative_data_relationships:
      properties:
        chat:
          $ref: '#/components/schemas/LinksDirect'
        likes:
          $ref: '#/components/schemas/LinksDirect'
        reposts:
          $ref: '#/components/schemas/LinksDirect'
        reports:
          $ref: '#/components/schemas/LinksDirect'
      required:
      - chat
      - likes
      - reports
      - reposts
      type: object
    Initiative_data:
      properties:
        id:
          description: initiative id
          type: string
        type:
          enum:
          - initiative
          type: string
        attributes:
          $ref: '#/components/schemas/Initiative_data_attributes'
        links:
          $ref: '#/components/schemas/LinkSelf'
        relationships:
          $ref: '#/components/schemas/Initiative_data_relationships'
      required:
      - attributes
      - id
      - links
      - relationships
      - type
    Initiative_included:
      properties:
        wallets:
          $ref: '#/components/schemas/Wallets'
        organization:
          items:
            $ref: '#/components/schemas/AddOrgMember'
          type: array
      required:
      - organization
      - tags
      - wallets
    InitiativeCreate_data_attributes:
      properties:
        name:
          description: name of initiative
          type: string
        desc:
          description: description of initiative
          type: string
        goal:
          description: goal of initiative
          type: string
        location:
          description: location of initiative
          type: string
        type:
          description: types of initiative
          type: string
        status:
          description: status of initiative
          type: string
        final_cost:
          description: final cost of initiative
          format: int64
          type: integer
        org_id:
          description: organization id
          type: string
        wallets:
          $ref: '#/components/schemas/Wallets'
      required:
      - desc
      - final_cost
      - goal
      - name
      - org_id
      - status
      - type
      - wallets
      type: object
    InitiativeCreate_data:
      properties:
        type:
          enum:
          - initiative
          type: string
        attributes:
          $ref: '#/components/schemas/InitiativeCreate_data_attributes'
      required:
      - attributes
      - relationships
      - type
    InitiativeUpdate_data_attributes:
      properties:
        name:
          description: name of initiative
          type: string
        desc:
          description: description of initiative
          type: string
        goal:
          description: goal of initiative
          type: string
        location:
          description: location of initiative
          type: string
        type:
          description: types of initiative
          type: string
        status:
          description: status of initiative
          type: string
        final_cost:
          description: final cost of initiative
          format: int64
          type: integer
        wallets:
          $ref: '#/components/schemas/Wallets'
        org_members:
          items:
            $ref: '#/components/schemas/AddOrgMember'
          type: array
      type: object
    InitiativeUpdate_data:
      properties:
        type:
          enum:
          - initiative
          type: string
        attributes:
          $ref: '#/components/schemas/InitiativeUpdate_data_attributes'
      required:
      - attributes
      - type
    Wallets_bank_account:
      properties:
        monobank:
          description: monobank account
          type: string
        privat:
          description: privat account
          type: string
      type: object
    Wallets_payment_system:
      properties:
        pay_pal:
          description: paypal account
          type: string
        apple_pay:
          description: apple pay account
          type: string
        google_pay:
          description: google pay account
          type: string
      type: object
    Wallets_crypto_wallets:
      properties:
        USDT:
          description: USDT wallet
          type: string
        ETH:
          description: ETH wallet
          type: string
        BTC:
          description: BTC wallet
          type: string
        TON:
          description: TON wallet
          type: string
        SOL:
          description: SOL wallet
          type: string
      type: object
    WalletsUpdate_data:
      properties:
        type:
          enum:
          - wallets_update
          type: string
        attributes:
          $ref: '#/components/schemas/Wallets'
      required:
      - attributes
      - type
    AddOrgMember_data_attributes:
      properties:
        org_id:
          description: organization id
          type: string
        status:
          description: status of member
          type: string
      required:
      - org_id
      - status
      type: object
    AddOrgMember_data:
      properties:
        type:
          enum:
          - org_member_add
          type: string
        attributes:
          $ref: '#/components/schemas/AddOrgMember_data_attributes'
      required:
      - attributes
      - type
    LinksDirect_links:
      properties:
        self:
          description: Link to participants
          type: string
        related:
          description: Link to participants
          type: string
      required:
      - data
      - related
      - self
      type: object
    LinksDirect_data:
      properties:
        id:
          description: resources id
          type: string
        type:
          description: resources type
          type: string
      required:
      - id
      - type
      type: object
