openapi: 3.0.3
info:
  description: example
  title: test
  version: 0.0.0
servers:
- url: /
paths:
  /test:
    post:
      operationId: test
      responses:
        "201":
          description: Ok
      summary: Test
components:
  schemas:
    LinksDirect:
      properties:
        links:
          $ref: '#/components/schemas/LinksDirect_links'
        data:
          $ref: '#/components/schemas/LinksDirect_data'
      required:
      - links
      type: object
    LinksPagination:
      properties:
        previous:
          description: Link to the previous page
          type: string
        self:
          description: Link to the current page
          type: string
        next:
          description: Link to the next page
          type: string
      required:
      - next
      - previous
      - self
      type: object
    Initiative:
      properties:
        data:
          $ref: '#/components/schemas/Initiative_data'
        included:
          $ref: '#/components/schemas/Initiative_included'
      required:
      - data
      type: object
    InitiativeCreate:
      properties:
        data:
          $ref: '#/components/schemas/InitiativeCreate_data'
      required:
      - data
      type: object
    InitiativeUpdate:
      properties:
        data:
          $ref: '#/components/schemas/InitiativeUpdate_data'
      required:
      - data
      - included
      type: object
    LinksDirect_links:
      properties:
        self:
          description: Link to participants
          type: string
        related:
          description: Link to participants
          type: string
      required:
      - related
      - self
      type: object
    LinksDirect_data:
      properties:
        id:
          description: resources id
          type: string
        type:
          description: resources type
          type: string
      required:
      - id
      - type
      type: object
    Initiative_data_attributes:
      properties:
        name:
          description: name of initiative
          type: string
        desc:
          description: description of initiative
          type: string
        goal:
          description: goal of initiative
          type: string
        verified:
          description: verified status
          type: boolean
        location:
          description: location of initiative
          type: string
        type:
          description: types of initiative
          type: string
        status:
          description: status of initiative
          type: string
        final_cost:
          description: final cost of initiative
          format: int64
          type: integer
        collected_sum:
          description: collected sum of initiative
          format: int64
          type: integer
        likes:
          description: likes of initiative
          format: int64
          type: integer
        reposts:
          description: reposts of initiative
          format: int64
          type: integer
        reports:
          description: reports of initiative
          format: int64
          type: integer
        start_at:
          description: start date of initiative
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        end_at:
          description: end date of initiative
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        updated_at:
          description: Initiative updated at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        closed_at:
          description: Initiative closed at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - desc
      - goal
      - likes
      - name
      - reports
      - reposts
      - status
      - type
      - verified
      type: object
    Initiative_data_relationships:
      properties:
        chat:
          $ref: ./spec/components/schemas/LinksDirect.yaml
        likes:
          $ref: ./spec/components/schemas/LinksDirect.yaml
        reposts:
          $ref: ./spec/components/schemas/LinksDirect.yaml
        reports:
          $ref: ./spec/components/schemas/LinksDirect.yaml
        participants:
          $ref: ./spec/components/schemas/LinksDirect.yaml
        points:
          $ref: ./spec/components/schemas/LinksDirect.yaml
      required:
      - chat
      - likes
      - participants
      - points
      - reports
      - reposts
      type: object
    Initiative_data:
      properties:
        id:
          description: initiative id
          type: string
        type:
          enum:
          - initiative
          type: string
        attributes:
          $ref: '#/components/schemas/Initiative_data_attributes'
        links:
          $ref: ./spec/components/schemas/LinkSelf.yaml
        relationships:
          $ref: '#/components/schemas/Initiative_data_relationships'
      required:
      - attributes
      - id
      - links
      - relationships
      - type
      type: object
    Initiative_included:
      properties:
        wallets:
          $ref: ./spec/components/schemas/Wallets.yaml
        organization:
          items:
            $ref: ./spec/components/schemas/OrgMember.yaml
          type: array
      required:
      - organization
      - tags
      - wallets
      type: object
    InitiativeCreate_data_attributes:
      properties:
        name:
          description: name of initiative
          type: string
        desc:
          description: description of initiative
          type: string
        goal:
          description: goal of initiative
          type: string
        location:
          description: location of initiative
          type: string
        type:
          description: types of initiative
          type: string
        status:
          description: status of initiative
          type: string
        final_cost:
          description: final cost of initiative
          format: int64
          type: integer
        wallets:
          $ref: ./spec/components/schemas/Wallets.yaml
        org_members:
          items:
            $ref: ./spec/components/schemas/OrgMember.yaml
          type: array
      required:
      - desc
      - final_cost
      - goal
      - name
      - org_members
      - status
      - type
      - wallets
      type: object
    InitiativeCreate_data:
      properties:
        type:
          enum:
          - initiative_create
          type: string
        attributes:
          $ref: '#/components/schemas/InitiativeCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    InitiativeUpdate_data:
      properties:
        type:
          enum:
          - initiative_update
          type: string
        attributes:
          $ref: '#/components/schemas/InitiativeCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
