openapi: 3.0.3
info:
  title: test
  description: example
  version: 0.0.0

paths:
  /test:
    post:
      summary: Test
      operationId: test
      responses:
        '201':
          description: "Ok"

components:
  schemas:
    LinksDirect:
      $ref: './spec/components/schemas/LinksDirect.yaml'
    LinksPagination:
      $ref: './spec/components/schemas/LinksPagination.yaml'
    Initiative:
      $ref: './spec/components/schemas/Initiative.yaml'
    InitiativeCreate:
      $ref: './spec/components/schemas/InitiativeCreate.yaml'
    InitiativeUpdate:
      $ref: './spec/components/schemas/InitiativeUpdate.yaml'